import Foundation

/// The stage table: which package owns each stage, and what a reader is shown for it.
///
/// Split out of `PipelineStage.swift` when adding `argumentAttribution` pushed that file past
/// SwiftLint's 500-line limit. The enum keeps the cases and the reasoning; this keeps the two
/// mappings a test asserts over.
extension PipelineStage {
    var id: String { rawValue }

    /// The package that owns this stage, shown in Diagnostics so the mapping is explicit.
    var package: String {
        switch self {
        case .explorationChannel: return "ExplorationChannelKit"
        case .labelReturn: return "LabelReturnKit"
        case .delaySignal: return "DelaySignalKit"
        case .delayShape: return "DelayShapeKit"
        case .delayCurve: return "DelayCurveKit"
        case .curveDivergence: return "CurveDivergenceKit"
        case .labelClock: return "LabelClockKit"
        case .effectiveVote: return "EffectiveVoteKit"
        case .proxyLabel: return "ProxyLabelKit"
        case .sampleWidth: return "SampleWidthKit"
        case .familyError: return "FamilyErrorKit"
        case .effectiveComparison: return "EffectiveComparisonKit"
        case .observedNull: return "ObservedNullKit"
        case .chanceAgreement: return "ChanceAgreementKit"
        case .panelDesign: return "PanelDesignKit"
        case .squareDesign: return "SquareDesignKit"
        case .associationFit: return "AssociationFitKit"
        case .associationTransport: return "AssociationTransportKit"
        case .exactAssociation: return "ExactAssociationKit"
        case .conditioningCost: return "ConditioningCostKit"
        case .unconditionalExact: return "UnconditionalExactKit"
        case .totalFixedExact: return "TotalFixedExactKit"
        case .restrictionRule: return "RestrictionRuleKit"
        case .repeatedSuccess: return "RepeatedSuccessKit"
        case .sequentialBound: return "SequentialBoundKit"
        case .confidenceSequence: return "ConfidenceSequenceKit"
        case .sequentialContrast: return "SequentialContrastKit"
        case .splitContrast: return "SplitContrastKit"
        case .promptCache: return "PromptCacheKit"
        case .compactionPlan: return "CompactionPlannerKit"
        case .fleetRollout: return "FleetRolloutKit"
        case .toolIntegrity: return "ToolIntegrityKit"
        case .promptTemplate: return "PromptTemplateKit"
        case .lexicalRetrieval, .rankFusion: return "SpotlightRAGKit"
        case .transcriptCapture: return "EvalHarness"
        case .guardrailInput, .guardrailOutput: return "GuardrailKit"
        case .semanticRoute: return "SemanticRouterKit"
        case .idempotencyGuard: return "IdempotencyKit"
        case .cacheLookup: return "ResponseCacheKit"
        case .memoryRecall: return "AgentMemoryKit"
        case .retrieval: return "RetrievalKit"
        case .contextCompaction: return "ContextCompactionKit"
        case .workloadProfile: return "WorkloadProfilerKit"
        case .costForecast: return "CostEstimatorKit"
        case .budgetReserve, .budgetSettle: return "QuotaGovernorKit"
        case .retryPolicy: return "RetryPolicyKit"
        case .hedgedRequest: return "HedgedRequestKit"
        case .modelCascade: return "ModelCascadeKit"
        case .providerRouting: return "ProviderGatewayKit"
        case .streamAggregation: return "StreamAggregatorKit"
        case .streamRelease: return "StreamReleaseKit"
        case .sessionDelivery: return "RealtimeSessionKit"
        case .structuredDecode: return "StructuredOutputKit"
        case .outputRepair: return "OutputRepairKit"
        case .schemaMigration: return "SchemaMigrationKit"
        case .grounding: return "GroundingKit"
        case .claimSegmentation: return "ClaimSegmenterKit"
        case .claimConsistency: return "ClaimConsistencyKit"
        case .citationBinding: return "CitationBindingKit"
        case .claimDecontextualization: return "ClaimDecontextualizerKit"
        case .sourceConflict: return "SourceConflictKit"
        case .evidenceKeying: return "MorphologyMatchKit"
        case .answerabilityGate: return "AnswerabilityKit"
        case .temporalValidity: return "TemporalValidityKit"
        case .sourceIndependence: return "SourceIndependenceKit"
        case .verdictStability: return "EvidenceSensitivityKit"
        case .signalDependence: return "SignalDependenceKit"
        case .abstentionArbiter: return "AbstentionPolicyKit"
        case .conformalGate: return "ConformalGateKit"
        case .censoredFeedback: return "CensoredFeedbackKit"
        case .scopeDrift: return "ScopeDriftKit"
        case .toolAuthority: return "ToolAuthorityKit"
        case .selectionTrust: return "SelectionTrustKit"
        case .argumentAttribution: return "ArgumentAttributionKit"
        case .toolCallScheduling: return "ToolCallSchedulerKit"
        case .toolDispatch: return "ToolRegistryKit"
        case .outcomeMonitor: return "OutcomeMonitorKit"
        case .verifiedCall: return "VerifiedCallKit"
        case .agentLoop: return "AgentLoopKit"
        case .loopGuard: return "LoopGuardKit"
        case .progressGate: return "ProgressGateKit"
        case .batchInference: return "BatchInferenceKit"
        case .metering: return "TokenMeterKit"
        case .tracing: return "TraceKit"
        }
    }

    /// What this stage is for, in the words a Diagnostics reader needs.
    var title: String {
        switch self {
        case .promptTemplate: return "Prompt template"
        case .guardrailInput: return "Input guardrail"
        case .semanticRoute: return "Semantic route"
        case .idempotencyGuard: return "Idempotency guard"
        case .cacheLookup: return "Cache lookup"
        case .memoryRecall: return "Memory recall"
        case .retrieval: return "Retrieval"
        case .lexicalRetrieval: return "Lexical retrieval"
        case .rankFusion: return "Rank fusion"
        case .transcriptCapture: return "Transcript capture"
        case .contextCompaction: return "Context compaction"
        case .evidenceKeying: return "Evidence keying"
        case .answerabilityGate: return "Answerability gate"
        case .temporalValidity: return "Temporal validity"
        case .sourceIndependence: return "Source independence"
        case .verdictStability: return "Verdict stability"
        case .signalDependence: return "Signal dependence"
        case .abstentionArbiter: return "Abstention arbiter"
        case .conformalGate: return "Conformal gate"
        case .censoredFeedback: return "Censored feedback"
        case .explorationChannel: return "Exploration channel"
        case .labelReturn: return "Label return"
        case .delaySignal: return "Delay signal"
        case .delayShape: return "Delay shape"
        case .delayCurve: return "Delay curve"
        case .curveDivergence: return "Curve divergence"
        case .labelClock: return "Label clock"
        case .effectiveVote: return "Effective vote"
        case .proxyLabel: return "Proxy label"
        case .sampleWidth: return "Sample width"
        case .familyError: return "Family error"
        case .effectiveComparison: return "Effective comparison"
        case .observedNull: return "Observed null"
        case .chanceAgreement: return "Chance agreement"
        case .panelDesign: return "Panel design"
        case .squareDesign: return "Square design"
        case .associationFit: return "Association fit"
        case .associationTransport: return "Association transport"
        case .exactAssociation: return "Exact association"
        case .conditioningCost: return "Conditioning cost"
        case .unconditionalExact: return "Unconditional exact"
        case .totalFixedExact: return "Total-fixed exact"
        case .restrictionRule: return "Restriction rule"
        case .repeatedSuccess: return "Repeated success"
        case .sequentialBound: return "Sequential bound"
        case .confidenceSequence: return "Confidence sequence"
        case .sequentialContrast: return "Sequential contrast"
        case .splitContrast: return "Split contrast"
        case .promptCache: return "Prompt cache"
        case .compactionPlan: return "Compaction plan"
        case .fleetRollout: return "Fleet rollout gate"
        case .toolIntegrity: return "Tool integrity"
        case .workloadProfile: return "Workload profile"
        case .costForecast: return "Cost forecast"
        case .budgetReserve: return "Budget reserve"
        case .retryPolicy: return "Retry policy"
        case .hedgedRequest: return "Hedged request"
        case .modelCascade: return "Model cascade"
        case .providerRouting: return "Provider routing"
        case .streamAggregation: return "Stream aggregation"
        case .streamRelease: return "Live stream release"
        case .sessionDelivery: return "Session delivery"
        case .structuredDecode: return "Structured decode"
        case .outputRepair: return "Output repair"
        case .schemaMigration: return "Schema migration"
        case .grounding: return "Grounding"
        case .claimSegmentation: return "Claim segmentation"
        case .claimConsistency: return "Claim consistency"
        case .citationBinding: return "Citation binding"
        case .claimDecontextualization: return "Claim decontextualization"
        case .sourceConflict: return "Source conflict"
        case .scopeDrift: return "Scope drift"
        case .toolAuthority: return "Tool authority"
        case .selectionTrust: return "Selection trust"
        case .argumentAttribution: return "Argument attribution"
        case .toolCallScheduling: return "Tool call scheduling"
        case .toolDispatch: return "Tool dispatch"
        case .outcomeMonitor: return "Tool outcome check"
        case .verifiedCall: return "Verify before retry"
        case .agentLoop: return "Agent loop"
        case .loopGuard: return "Loop guard"
        case .progressGate: return "Completion check"
        case .batchInference: return "Batch inference"
        case .guardrailOutput: return "Output guardrail"
        case .metering: return "Metering"
        case .budgetSettle: return "Budget settle"
        case .tracing: return "Tracing"
        }
    }
}
